### ISSUE TITLE
Unbinding narrator toggle sets keybind to media keys.

### ISSUE THREAD

**Issue by athompson673** [Ocraftyone/rebindnarrator#1]
>If, for say I unbind the cmd. It binds itself to "fn+f5/f6" for me which are media buttons

This was [commented](https://www.curseforge.com/minecraft/mc-mods/rebindnarrator?comment=8) on the curse forge page, but I wanted to say I'm having exactly the same issue.

**Comment by Peekofwar** [comment]
I just encountered this too, though I think the origin of this bug is related to the game itself.

That said, perhaps a check could be put in place that checks the keybind, and if it's unbound, block the action from occurring.

**Comment by Peekofwar** [comment]
I guess you could bind it to `SHIFT+LWIN`.

**Comment by Ocraftyone** [comment]
> > If, for say I unbind the cmd. It binds itself to "fn+f5/f6" for me which are media buttons
> 
> This was [commented](https://www.curseforge.com/minecraft/mc-mods/rebindnarrator?comment=8) on the curse forge page, but I wanted to say I'm having exactly the same issue.

I apologize for it taking me so long to look into this.

> I just encountered this too, though I think the origin of this bug is related to the game itself.
> 
> That said, perhaps a check could be put in place that checks the keybind, and if it's unbound, block the action from occurring.

Yup! You are right! I did find a way to patch it so if it is unbound, it prevents the narrator from being invoked. New files are coming soon!
