### ISSUE TITLE
Nees Language Provider `javafml:41` or above Crash

### ISSUE THREAD

**Issue by Peekofwar** [Ocraftyone/rebindnarrator#2]
After updating to v1.2.1, the game crashes on startup with the following error:
```
Mod File rebindnarrator-1.2.1.jar needs language provider javafml:41 or above to load
We have found 40
```

Minecraft `v1.18.2`
Forge `v40.1.60`

**Comment by Peekofwar** [comment]
Ah, I see. I downloaded a version that's for MC v1.19

**Comment by Ocraftyone** [comment]
Yup! 1.19 has some incompatibilities in the ways keybinds are registered, so unfortunately I can't use one file for all versions.

**Comment by Peekofwar** [comment]
> Yup! 1.19 has some incompatibilities in the ways keybinds are registered, so unfortunately I can't use one file for all versions.

As far as I know, most mods that have different files for the different game versions use the same version number for the mod. That probably threw me off a little since yours have two different mod versions for the different game versions. 

_What I'm use to:_
`somemodfile-1.18.2-1.2.0.jar`
`somemodfile-1.19-1.2.0.jar`

**Comment by Ocraftyone** [comment]
just reworked my workflow for publishing, ill keep this in mind in the future and I will see about adding display names on curseforge to hopefully alleviate that issue.
